filesystem:
  service: Disk
  root: <%= Rails.root.join('storage') %>
s3:
  service: S3
  access_key_id: <%= Rails.configuration.alonetone.amazon_access_key_id %>
  secret_access_key: <%= Rails.configuration.alonetone.amazon_secret_access_key %>
  region: <%= Rails.configuration.alonetone.amazon_s3_region %>
  bucket: <%= Rails.configuration.alonetone.amazon_s3_bucket_name %>
  # Keys in the `upload' section are forwarded to the Aws::S3::Object#put
  # method when uploading all files. By default we require a signed URL
  # to access files.
  upload:
    acl: authenticated-read
